USE [tpcc]
GO

/****** Object:  Index [STOCK_I1]    Script Date: 30-04-2014 10:56:01 ******/
CREATE UNIQUE NONCLUSTERED INDEX [STOCK_I1] ON [dbo].[STOCK]
(
	[s_i_id] ASC,
	[s_w_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


